### ISSUE TITLE
blastn not used anymore?

### ISSUE THREAD

**Issue by keuv-grvl** [songweizhi/Binning_refiner#2]
Dear,

As described in your paper, "The bins from each binning program are then combined into one file and a pairwise blastn (Altschul et al., 1990) is performed between the two combined files". But it seems that `blastn` is only used in the version 1.0 and not in latest version. Is there any documentation to explain this change?

Thank you.

**Comment by songweizhi** [comment]
Hi,

Thanks for your inquiry. Yes, the blastn approach has been disabled in the later version. I have just added a detailed explanation to the "Change Log" section in the manual.

Best,
Weizhi

**Comment by keuv-grvl** [comment]
Oops, my bad... I did not see this part.

Maybe you could propose a [release](https://github.com/songweizhi/Binning_refiner/releases) of the orginal Binning_refiner algorithm for users who may want to reuse the version described in your paper.

**Comment by songweizhi** [comment]
Good point, 
the blast-based version has been added to the repository for users who may want to try, although it was not recommended.

Weizhi
