### ISSUE TITLE
More than 3 binning softwares

### ISSUE THREAD

**Issue by palomo11** [songweizhi/Binning_refiner#3]
Hi,

I have been using binning refiner and it gives very good output. But I wonder if at some point it is going to be possible to use the output from more than 3 different binning softwares.

Thanks in advance.

**Comment by songweizhi** [comment]
Hi, Binning_refiner currently only support for no more than three binning programs. However, there is a tricky way to do this: you can combine your bin sets by merging three of them first and then combine the resulting output with the rest.

Weizhi
